INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I01', 'Thiệp handmade vintage Beauty ', 'images/products/.webp', 'P01');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I02', 'Thiệp handmade vintage Beauty ', 'images/products/.webp', 'P01');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I03', 'Thiệp handmade vintage Beauty ', 'images/products/.webp', 'P01');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I04', 'Thiệp handmade Film de Paris', 'images/products/.webp', 'P02');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I05', 'Thiệp handmade Film de Paris', 'images/products/.webp', 'P02');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I06', 'Thiệp handmade Film de Paris', 'images/products/.webp', 'P02');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I07', 'Thiệp chúc mừng Sweet Mint', 'images/products/.webp', 'P03');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I08', 'Thiệp chúc mừng Sweet Mint', 'images/products/.webp', 'P03');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I09', 'Thiệp chúc mừng Sweet Mint', 'images/products/.webp', 'P03');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I10', 'Thiệp chúc mừng Black & White', 'images/products/.webp', 'P04');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I100', 'Scrapbook Fly That Time', 'images/products/p44.webp', 'P43');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I101', 'Album ảnh handmade Fly Sweet M', 'images/products/p44_1.webp', 'P44');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I102', 'Album ảnh handmade Fly Sweet M', 'images/products/p44_2.webp', 'P44');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I103', 'Album ảnh handmade Fly Sweet M', 'images/products/p45.webp', 'P44');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I104', 'Album ảnh tự trang trí Love St', 'images/products/p45_1.webp', 'P45');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I105', 'Album ảnh tự trang trí Love St', 'images/products/p45_2.webp', 'P45');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I106', 'Album ảnh tự trang trí Love St', 'images/products/p46.webp', 'P45');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I107', 'Scrapbook Retro Clock', 'images/products/p46_1.webp', 'P46');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I108', 'Scrapbook Retro Clock', 'images/products/p46_2.webp', 'P46');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I109', 'Scrapbook Retro Clock', 'images/products/p47.webp', 'P46');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I11', 'Thiệp chúc mừng Black & White', 'images/products/p04.webp', 'P04');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I110', 'Scrapbook Vintage', 'images/products/p47_1.webp', 'P47');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I111', 'Scrapbook Vintage', 'images/products/p48.webp', 'P47');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I112', 'Scrapbook Lò Xo Handmade Phong', 'images/products/p48_1.webp', 'P48');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I113', 'Scrapbook Lò Xo Handmade Phong', 'images/products/p48_2.webp', 'P48');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I114', 'Scrapbook Lò Xo Handmade Phong', 'images/products/p49.webp', 'P48');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I115', 'Album ảnh handmade Blue Pastel', 'images/products/p49_1.webp', 'P49');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I116', 'Album ảnh handmade Blue Pastel', 'images/products/p49_2.webp', 'P49');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I117', 'Album ảnh handmade Blue Pastel', 'images/products/p50.webp', 'P49');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I118', 'Scrapbook My Boy For The Memor', 'images/products/p50_1.webp', 'P50');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I119', 'Scrapbook My Boy For The Memor', 'images/products/p50_2.webp', 'P50');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I12', 'Thiệp chúc mừng Black & White', 'images/products/p05.webp', 'P04');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I120', 'Scrapbook My Boy For The Memor', 'images/products/p51.webp', 'P50');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I121', 'Scrapbook Lò Xo Handmade Trang', 'images/products/p51_1.webp', 'P51');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I122', 'Scrapbook Lò Xo Handmade Trang', 'images/products/p51_2.webp', 'P51');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I123', 'Scrapbook Lò Xo Handmade Trang', 'images/products/p52.webp', 'P51');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I124', 'Scrapbook Film de Paris', 'images/products/p52_1.webp', 'P52');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I125', 'Scrapbook Film de Paris', 'images/products/p52_2.webp', 'P52');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I126', 'Scrapbook Film de Paris', 'images/products/p53.webp', 'P52');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I127', 'Scrapbook handmade Sweet Momen', 'images/products/p53_1.webp', 'P53');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I128', 'Scrapbook handmade Sweet Momen', 'images/products/p53_2.webp', 'P53');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I129', 'Scrapbook handmade Sweet Momen', 'images/products/p54.webp', 'P53');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I13', 'Thiệp handmade Amazing Carto', 'images/products/p05_1.webp', 'P05');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I130', 'SCRAPBOOK CHỦ ĐỀ CHO BÉ', 'images/products/p54_1.webp', 'P54');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I131', 'SCRAPBOOK CHỦ ĐỀ CHO BÉ', 'images/products/p54_2.webp', 'P54');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I132', 'SCRAPBOOK CHỦ ĐỀ CHO BÉ', 'images/products/p55.webp', 'P54');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I133', 'Fly album handmade bicycle', 'images/products/p55_1.webp', 'P55');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I134', 'Fly album handmade bicycle', 'images/products/p55_2.webp', 'P55');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I135', 'Fly album handmade bicycle', 'images/products/p56.webp', 'P55');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I136', 'Fly album handmade Blue Pastel', 'images/products/p56_1.webp', 'P56');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I137', 'Fly album handmade Blue Pastel', 'images/products/p56_2.webp', 'P56');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I138', 'Fly album handmade Blue Pastel', 'images/products/p57.webp', 'P56');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I139', 'Fly album Love (Xanh)', 'images/products/p57_1.webp', 'P57');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I14', 'Thiệp handmade Amazing Carto', 'images/products/p05_2.webp', 'P05');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I140', 'Fly album Love (Xanh)', 'images/products/p57_2.webp', 'P57');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I141', 'Fly album Love (Xanh)', 'images/products/p58.webp', 'P57');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I142', 'Fly album Sweet Moment', 'images/products/p58_1.webp', 'P58');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I143', 'Fly album Sweet Moment', 'images/products/p59.webp', 'P58');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I144', 'Fly album Retro Clock', 'images/products/p59_1.webp', 'P59');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I145', 'Fly album Retro Clock', 'images/products/p60.webp', 'P59');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I146', 'Scrapbook độc đáo cho tình yêu', 'images/products/p60_1.webp', 'P60');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I147', 'Scrapbook độc đáo cho tình yêu', 'images/products/p60_2.webp', 'P60');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I148', 'Scrapbook độc đáo cho tình yêu', 'images/products/p61.webp', 'P60');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I149', 'Album DIY Retro Clock', 'images/products/p61_1.webp', 'P61');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I15', 'Thiệp handmade Amazing Carto', 'images/products/p06.webp', 'P05');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I150', 'Album DIY Retro Clock', 'images/products/p61_2.webp', 'P61');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I151', 'Album DIY Retro Clock', 'images/products/p62.webp', 'P61');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I152', 'Scrapbook LIVE,LAUGH,LOVE', 'images/products/p62_1.webp', 'P62');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I153', 'Scrapbook LIVE,LAUGH,LOVE', 'images/products/p62_2.webp', 'P62');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I154', 'Scrapbook LIVE,LAUGH,LOVE', 'images/products/p63.webp', 'P62');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I155', 'Scrapbook Were Growing', 'images/products/p63_1.webp', 'P63');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I156', 'Scrapbook Were Growing', 'images/products/p63_2.webp', 'P63');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I157', 'Scrapbook Were Growing', 'images/products/p64.webp', 'P63');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I158', 'Scrapbook JUST BE ME', 'images/products/p64_1.webp', 'P64');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I159', 'Scrapbook JUST BE ME', 'images/products/p65.webp', 'P64');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I16', 'Thiệp handmade lớn Beauty & th', 'images/products/p06_1.webp', 'P06');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I160', 'SCRAPBOOK CHỦ ĐỀ TÌNH YÊU', 'images/products/p65_1.webp', 'P65');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I161', 'SCRAPBOOK CHỦ ĐỀ TÌNH YÊU', 'images/products/p66.webp', 'P65');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I162', 'Scrapbook MY LITTLE PRINCESS', 'images/products/p66_1.webp', 'P66');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I163', 'Scrapbook MY LITTLE PRINCESS', 'images/products/p66_2.webp', 'P66');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I164', 'Scrapbook MY LITTLE PRINCESS', 'images/products/p67.webp', 'P66');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I165', 'Album handmade bé trai MY LITT', 'images/products/p68.webp', 'P67');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I166', 'Album ảnh bé trai Wonderful My', 'images/products/p68_1.webp', 'P68');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I167', 'Album ảnh bé trai Wonderful My', 'images/products/p69.webp', 'P68');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I168', 'Scrapbook cao cấp My little pr', 'images/products/p69_1.webp', 'P69');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I169', 'Scrapbook cao cấp My little pr', 'images/products/p70.webp', 'P69');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I17', 'Thiệp handmade lớn Beauty & th', 'images/products/p06_2.webp', 'P06');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I170', 'Scrapbook handmade Darling Dau', 'images/products/p70_1.webp', 'P70');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I171', 'Scrapbook handmade Darling Dau', 'images/products/p71.webp', 'P70');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I172', 'Scrapbook cao cấp I am marvelo', 'images/products/p72.webp', 'P71');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I173', 'Scrapbook cao cấp My boy', 'images/products/p73.webp', 'P72');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I174', 'Album cưới handmade Beautiful ', 'images/products/p73_1.webp', 'P73');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I175', 'Album cưới handmade Beautiful ', 'images/products/p74.webp', 'P73');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I176', 'Album handmade scrapbook đẹp T', 'images/products/p74_1.webp', 'P74');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I177', 'Album handmade scrapbook đẹp T', 'images/products/p74_2.webp', 'P74');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I178', 'Album handmade scrapbook đẹp T', 'images/products/p75.webp', 'P74');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I179', 'Scrapbook cao cấp Were growing', 'images/products/p75_1.webp', 'P75');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I18', 'Thiệp handmade lớn Beauty & th', 'images/products/p07.webp', 'P06');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I180', 'Scrapbook cao cấp Were growing', 'images/products/p75_2.webp', 'P75');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I181', 'Scrapbook cao cấp Were growing', 'images/products/p76.webp', 'P75');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I182', 'Album ảnh handmade I am Marvel', 'images/products/p76_1.webp', 'P76');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I183', 'Album ảnh handmade I am Marvel', 'images/products/p76_2.webp', 'P76');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I184', 'Album ảnh handmade I am Marvel', 'images/products/p77.webp', 'P76');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I185', 'Flying album handmade Love Sto', 'images/products/p77_1.webp', 'P77');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I186', 'Flying album handmade Love Sto', 'images/products/p77_2.webp', 'P77');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I187', 'Flying album handmade Love Sto', 'images/products/p78.webp', 'P77');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I188', 'Flying album handmade Somewher', 'images/products/p78_1.webp', 'P78');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I189', 'Flying album handmade Somewher', 'images/products/p78_2.webp', 'P78');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I19', 'Thiệp da bò độc đáo', 'images/products/p07_1.webp', 'P07');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I190', 'Flying album handmade Somewher', 'images/products/p79.webp', 'P78');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I191', 'Flying album handmade A Moment', 'images/products/p79_1.webp', 'P79');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I192', 'Flying album handmade A Moment', 'images/products/p79_2.webp', 'P79');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I193', 'Flying album handmade A Moment', 'images/products/p80.webp', 'P79');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I194', 'Flying album vintage Memories', 'images/products/p80_1.webp', 'P80');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I195', 'Flying album vintage Memories', 'images/products/p80_2.webp', 'P80');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I196', 'Flying album vintage Memories', 'images/products/p81.webp', 'P80');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I197', 'Sổ ký tên đám cưới handmade', 'images/products/p81_1.webp', 'P81');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I198', 'Sổ ký tên đám cưới handmade', 'images/products/p81_2.webp', 'P81');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I199', 'Sổ ký tên đám cưới handmade', 'images/products/p82.webp', 'P81');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I20', 'Thiệp da bò độc đáo', 'images/products/p07_2.webp', 'P07');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I200', 'Exploding love box album handm', 'images/products/p82_1.webp', 'P82');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I201', 'Exploding love box album handm', 'images/products/p82_2.webp', 'P82');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I202', 'Exploding love box album handm', 'images/products/p83.webp', 'P82');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I203', 'Mini Love Card-Album Handmade', 'images/products/p83_1.webp', 'P83');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I204', 'Mini Love Card-Album Handmade', 'images/products/p83_2.webp', 'P83');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I205', 'Mini Love Card-Album Handmade', 'images/products/p84.webp', 'P83');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I206', 'ALBUM TỰ TRANG TRÍ (P,I) - SCR', 'images/products/p85.webp', 'P84');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I207', 'ALBUM TỰ TRANG TRÍ (P,II) - AL', 'images/products/p85_1.webp', 'P85');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I208', 'ALBUM TỰ TRANG TRÍ (P,II) - AL', 'images/products/p86.webp', 'P85');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I209', 'Album tự trang trí Vân gỗ trắn', 'images/products/p86_1.webp', 'P86');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I21', 'Thiệp da bò độc đáo', 'images/products/p08.webp', 'P07');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I210', 'Album tự trang trí Vân gỗ trắn', 'images/products/p86_2.webp', 'P86');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I211', 'Album tự trang trí Vân gỗ trắn', 'images/products/p87.webp', 'P86');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I212', 'Album DIY Vân gỗ Đỏ', 'images/products/p87_1.webp', 'P87');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I213', 'Album DIY Vân gỗ Đỏ', 'images/products/p87_2.webp', 'P87');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I214', 'Album DIY Vân gỗ Đỏ', 'images/products/p88.webp', 'P87');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I215', 'Album DIY Vân gỗ Pastel', 'images/products/p88_1.webp', 'P88');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I216', 'Album DIY Vân gỗ Pastel', 'images/products/p88_2.webp', 'P88');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I217', 'Album DIY Vân gỗ Pastel', 'images/products/p89.webp', 'P88');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I218', 'Album DIY Sọc nhỏ', 'images/products/p89_1.webp', 'P89');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I219', 'Album DIY Sọc nhỏ', 'images/products/p89_2.webp', 'P89');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I22', 'Thiệp dấu sáp mini', 'images/products/p08_1.webp', 'P08');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I220', 'Album DIY Sọc nhỏ', 'images/products/p90.webp', 'P89');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I221', 'Scrapbook handmade FOLIO', 'images/products/p90_1.webp', 'P90');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I222', 'Scrapbook handmade FOLIO', 'images/products/p90_2.webp', 'P90');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I223', 'Scrapbook handmade FOLIO', 'images/products/p91.webp', 'P90');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I224', 'Sổ ký tên handmade Save the da', 'images/products/p91_1.webp', 'P91');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I225', 'Sổ ký tên handmade Save the da', 'images/products/p91_2.webp', 'P91');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I226', 'Sổ ký tên handmade Save the da', 'images/products/p92.webp', 'P91');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I227', 'Sổ ký tên Our Story', 'images/products/p92_1.webp', 'P92');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I228', 'Sổ ký tên Our Story', 'images/products/p92_2.webp', 'P92');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I229', 'Sổ ký tên Our Story', 'images/products/p93.webp', 'P92');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I23', 'Thiệp dấu sáp mini', 'images/products/p08_2.webp', 'P08');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I230', 'Sổ ký tên ngày cưới Let me lov', 'images/products/p93_1.webp', 'P93');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I231', 'Sổ ký tên ngày cưới Let me lov', 'images/products/p94.webp', 'P93');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I232', 'Sổ ký tên Happy Light', 'images/products/p94_1.webp', 'P94');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I233', 'Sổ ký tên Happy Light', 'images/products/p94_2.webp', 'P94');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I234', 'Sổ ký tên Happy Light', 'images/products/p95.webp', 'P94');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I235', 'Sổ ký tên Happy Forest', 'images/products/p96.webp', 'P95');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I236', 'Sổ ký tên Tiny Love', 'images/products/p96_1.webp', 'P96');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I237', 'Sổ ký tên Tiny Love', 'images/products/p97.webp', 'P96');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I238', 'Album tự thiết kế Baby photo G', 'images/products/p97_1.webp', 'P97');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I239', 'Album tự thiết kế Baby photo G', 'images/products/p97_2.webp', 'P97');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I24', 'Thiệp dấu sáp mini', 'images/products/p09.webp', 'P08');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I240', 'Album tự thiết kế Baby photo G', 'images/products/p98.webp', 'P97');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I241', 'Guest Book Feeling good', 'images/products/p98_1.webp', 'P98');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I242', 'Guest Book Feeling good', 'images/products/p99.webp', 'P98');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I243', 'Guestbook - sổ ký tên đám cưới', 'images/products/p99_1.webp', 'P99');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I244', 'Guestbook - sổ ký tên đám cưới', 'images/products/p100.webp', 'P99');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I245', 'Album DIY gáy lò xo tiện dụng ', 'images/products/p100_1.webp', 'P100');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I246', 'Album DIY gáy lò xo tiện dụng ', 'images/products/p100_2.webp', 'P100');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I247', 'Album DIY gáy lò xo tiện dụng ', 'images/products/p101.webp', 'P100');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I248', 'Bình cắm hoa LYO', 'images/products/p101_1.webp', 'P101');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I249', 'Bình cắm hoa LYO', 'images/products/p101_2.webp', 'P101');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I25', 'Thiệp handmade Vintage Film', 'images/products/p09_1.webp', 'P09');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I250', 'Bình cắm hoa LYO', 'images/products/p102.webp', 'P101');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I251', 'Bình sứ trang trí Vintage', 'images/products/p102_1.webp', 'P102');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I252', 'Bình sứ trang trí Vintage', 'images/products/p102_2.webp', 'P102');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I253', 'Bình sứ trang trí Vintage', 'images/products/p103.webp', 'P102');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I254', 'Bình cắm hoa trang trí dây thừ', 'images/products/p103_1.webp', 'P103');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I255', 'Bình cắm hoa trang trí dây thừ', 'images/products/p103_2.webp', 'P103');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I256', 'Bình cắm hoa trang trí dây thừ', 'images/products/p104.webp', 'P103');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I257', 'Chai thủy tinh quấn thừng lớ', 'images/products/p104_1.webp', 'P104');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I258', 'Chai thủy tinh quấn thừng lớ', 'images/products/p104_2.webp', 'P104');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I259', 'Chai thủy tinh quấn thừng lớ', 'images/products/p105.webp', 'P104');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I26', 'Thiệp handmade Vintage Film', 'images/products/p09_2.webp', 'P09');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I260', 'Bình gốm cao giả cổ hoa văn vi', 'images/products/p105_1.webp', 'P105');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I261', 'Bình gốm cao giả cổ hoa văn vi', 'images/products/p105_2.webp', 'P105');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I262', 'Bình gốm cao giả cổ hoa văn vi', 'images/products/p106.webp', 'P105');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I263', 'Khay sứ giả cổ', 'images/products/p106_1.webp', 'P106');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I264', 'Khay sứ giả cổ', 'images/products/p106_2.webp', 'P106');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I265', 'Khay sứ giả cổ', 'images/products/p107.webp', 'P106');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I266', 'Giá để rượu vang gốm giả cổ', 'images/products/p107_1.webp', 'P107');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I267', 'Giá để rượu vang gốm giả cổ', 'images/products/p107_2.webp', 'P107');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I268', 'Giá để rượu vang gốm giả cổ', 'images/products/p108.webp', 'P107');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I269', 'Đế để rượu Nhân Sư Ai Cập', 'images/products/p108_1.webp', 'P108');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I27', 'Thiệp handmade Vintage Film', 'images/products/p10.webp', 'P09');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I270', 'Đế để rượu Nhân Sư Ai Cập', 'images/products/p108_2.webp', 'P108');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I271', 'Đế để rượu Nhân Sư Ai Cập', 'images/products/p109.webp', 'P108');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I272', 'Giá rượu Mèo Thần Ai Cập', 'images/products/p109_1.webp', 'P109');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I273', 'Giá rượu Mèo Thần Ai Cập', 'images/products/p110.webp', 'P109');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I274', 'Bình sứ Le Jardinier', 'images/products/p110_1.webp', 'P110');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I275', 'Bình sứ Le Jardinier', 'images/products/p111.webp', 'P110');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I276', 'Cốc vintage', 'images/products/p111_1.webp', 'P111');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I277', 'Cốc vintage', 'images/products/p111_2.webp', 'P111');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I278', 'Cốc vintage', 'images/products/p112.webp', 'P111');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I279', 'Ly sứ vintage phong cảnh châu ', 'images/products/p112_1.webp', 'P112');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I28', 'Thiệp handmade vintage vải bố', 'images/products/p10_1.webp', 'P10');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I280', 'Ly sứ vintage phong cảnh châu ', 'images/products/p112_2.webp', 'P112');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I281', 'Ly sứ vintage phong cảnh châu ', 'images/products/p113.webp', 'P112');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I282', 'Bình sứ xinh xắn Dream House', 'images/products/p113_1.webp', 'P113');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I283', 'Bình sứ xinh xắn Dream House', 'images/products/p113_2.webp', 'P113');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I284', 'Bình sứ xinh xắn Dream House', 'images/products/p114.webp', 'P113');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I285', 'Ly sứ starbucks coffee', 'images/products/p114_1.webp', 'P114');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I286', 'Ly sứ starbucks coffee', 'images/products/p114_2.webp', 'P114');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I287', 'Ly sứ starbucks coffee', 'images/products/p115.webp', 'P114');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I288', 'Ly sứ vintage street', 'images/products/p115_1.webp', 'P115');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I289', 'Ly sứ vintage street', 'images/products/p115_2.webp', 'P115');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I29', 'Thiệp handmade vintage vải bố', 'images/products/p10_2.webp', 'P10');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I290', 'Ly sứ vintage street', 'images/products/p116.webp', 'P115');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I291', 'Bình hoa gốm trắng GRID', 'images/products/p116_1.webp', 'P116');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I292', 'Bình hoa gốm trắng GRID', 'images/products/p116_2.webp', 'P116');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I293', 'Bình hoa gốm trắng GRID', 'images/products/p117.webp', 'P116');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I294', 'Bình hoa gốm giả cổ trang trí ', 'images/products/p117_1.webp', 'P117');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I295', 'Bình hoa gốm giả cổ trang trí ', 'images/products/p117_2.webp', 'P117');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I296', 'Bình hoa gốm giả cổ trang trí ', 'images/products/p118.webp', 'P117');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I297', 'Bình sứ giả cổ Victoria', 'images/products/p118_1.webp', 'P118');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I298', 'Bình sứ giả cổ Victoria', 'images/products/p119.webp', 'P118');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I299', 'Hộp đựng bút R102', 'images/products/p119_1.webp', 'P119');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I30', 'Thiệp handmade vintage vải bố', 'images/products/p11.webp', 'P10');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I300', 'Hộp đựng bút R102', 'images/products/p119_2.webp', 'P119');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I301', 'Hộp đựng bút R102', 'images/products/p120.webp', 'P119');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I302', 'Mèo thần tài R104', 'images/products/p120_1.webp', 'P120');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I303', 'Mèo thần tài R104', 'images/products/p120_2.webp', 'P120');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I304', 'Mèo thần tài R104', 'images/products/p121.webp', 'P120');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I305', 'Tượng Hươu trang trí R103', 'images/products/p121_1.webp', 'P121');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I306', 'Tượng Hươu trang trí R103', 'images/products/p121_2.webp', 'P121');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I307', 'Tượng Hươu trang trí R103', 'images/products/p122.webp', 'P121');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I308', 'Xe máy mô hình trang trí R101', 'images/products/p122_1.webp', 'P122');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I309', 'Xe máy mô hình trang trí R101', 'images/products/p122_2.webp', 'P122');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I31', 'Thiệp gỗ Jigsaws', 'images/products/p11_1.webp', 'P11');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I310', 'Xe máy mô hình trang trí R101', 'images/products/p123.webp', 'P122');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I311', 'Đèn bão trang trí Vintage', 'images/products/p123_1.webp', 'P123');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I312', 'Đèn bão trang trí Vintage', 'images/products/p123_2.webp', 'P123');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I313', 'Đèn bão trang trí Vintage', 'images/products/p124.webp', 'P123');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I314', 'Móc treo nữ trang vintage', 'images/products/p124_1.webp', 'P124');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I315', 'Móc treo nữ trang vintage', 'images/products/p125.webp', 'P124');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I316', 'Lọ hoa thủy tinh handmade', 'images/products/p125_1.webp', 'P125');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I317', 'Lọ hoa thủy tinh handmade', 'images/products/p126.webp', 'P125');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I318', 'Hoa lavender oải hương handmad', 'images/products/p126_1.webp', 'P126');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I319', 'Hoa lavender oải hương handmad', 'images/products/p126_2.webp', 'P126');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I32', 'Thiệp gỗ Jigsaws', 'images/products/p11_2.webp', 'P11');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I320', 'Hoa lavender oải hương handmad', 'images/products/p127.webp', 'P126');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I321', 'Hoa chậu handmade - Hoa hồng g', 'images/products/p127_1.webp', 'P127');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I322', 'Hoa chậu handmade - Hoa hồng g', 'images/products/p127_2.webp', 'P127');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I323', 'Hoa chậu handmade - Hoa hồng g', 'images/products/p128.webp', 'P127');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I324', 'Hộp nhạc piano pha lê khắc tê', 'images/products/p128_1.webp', 'P128');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I325', 'Hộp nhạc piano pha lê khắc tê', 'images/products/p128_2.webp', 'P128');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I326', 'Hộp nhạc piano pha lê khắc tê', 'images/products/p129.webp', 'P128');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I327', 'Hộp nhạc gỗ Piano', 'images/products/p129_1.webp', 'P129');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I328', 'Hộp nhạc gỗ Piano', 'images/products/p129_2.webp', 'P129');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I329', 'Hộp nhạc gỗ Piano', 'images/products/p130.webp', 'P129');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I33', 'Thiệp gỗ Jigsaws', 'images/products/p12.webp', 'P11');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I330', 'Hộp nhạc cổ điển camera', 'images/products/p130_1.webp', 'P130');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I331', 'Hộp nhạc cổ điển camera', 'images/products/p130_2.webp', 'P130');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I332', 'Hộp nhạc cổ điển camera', 'images/products/p131.webp', 'P130');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I333', 'Tượng trang trí phòng khách Th', 'images/products/p131_1.webp', 'P131');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I334', 'Tượng trang trí phòng khách Th', 'images/products/p131_2.webp', 'P131');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I335', 'Tượng trang trí phòng khách Th', 'images/products/p132.webp', 'P131');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I336', 'Tượng trang trí vintage không ', 'images/products/p132_1.webp', 'P132');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I337', 'Tượng trang trí vintage không ', 'images/products/p132_2.webp', 'P132');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I338', 'Tượng trang trí vintage không ', 'images/products/p133.webp', 'P132');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I339', 'Xe Vespa mô hình trang trí, ph', 'images/products/p133_1.webp', 'P133');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I34', 'Thiệp gỗ Other Half', 'images/products/p12_1.webp', 'P12');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I340', 'Xe Vespa mô hình trang trí, ph', 'images/products/p133_2.webp', 'P133');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I341', 'Xe Vespa mô hình trang trí, ph', 'images/products/p134.webp', 'P133');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I342', 'Thuyền gỗ vintage decor trang ', 'images/products/p134_1.webp', 'P134');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I343', 'Thuyền gỗ vintage decor trang ', 'images/products/p134_2.webp', 'P134');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I344', 'Thuyền gỗ vintage decor trang ', 'images/products/.webp', 'P134');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I35', 'Thiệp gỗ Other Half', 'images/products/p12_2.webp', 'P12');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I36', 'Thiệp gỗ Other Half', 'images/products/p13.webp', 'P12');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I37', 'Thiệp chúc mừng handmade Blue ', 'images/products/p13_1.webp', 'P13');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I38', 'Thiệp chúc mừng handmade Blue ', 'images/products/p13_2.webp', 'P13');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I39', 'Thiệp chúc mừng handmade Blue ', 'images/products/p14.webp', 'P13');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I40', 'Thiệp vintage Retro Clock', 'images/products/p14_1.webp', 'P14');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I41', 'Thiệp vintage Retro Clock', 'images/products/p14_2.webp', 'P14');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I42', 'Thiệp vintage Retro Clock', 'images/products/p15.webp', 'P14');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I43', 'Thiệp giấy carton handmade - T', 'images/products/p15_1.webp', 'P15');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I44', 'Thiệp giấy carton handmade - T', 'images/products/p15_2.webp', 'P15');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I45', 'Thiệp giấy carton handmade - T', 'images/products/p16.webp', 'P15');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I46', 'Thiệp tặng bạn thân - Thiệp vi', 'images/products/p16_1.webp', 'P16');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I47', 'Thiệp tặng bạn thân - Thiệp vi', 'images/products/p16_2.webp', 'P16');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I48', 'Thiệp tặng bạn thân - Thiệp vi', 'images/products/p17.webp', 'P16');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I49', 'Giấy viết thư cổ điển Vintage', 'images/products/p17_1.webp', 'P17');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I50', 'Giấy viết thư cổ điển Vintage', 'images/products/p17_2.webp', 'P17');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I51', 'Giấy viết thư cổ điển Vintage', 'images/products/p18.webp', 'P17');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I52', 'Khung ảnh đẹp Frame Triple', 'images/products/p18_1.webp', 'P18');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I53', 'Khung ảnh đẹp Frame Triple', 'images/products/p18_2.webp', 'P18');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I54', 'Khung ảnh đẹp Frame Triple', 'images/products/p19.webp', 'P18');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I55', 'Khung ảnh frame 6 in 1', 'images/products/p19_1.webp', 'P19');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I56', 'Khung ảnh frame 6 in 1', 'images/products/p19_2.webp', 'P19');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I57', 'Khung ảnh frame 6 in 1', 'images/products/p20.webp', 'P19');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I58', 'Khung ảnh gỗ 3 in 1', 'images/products/p20_1.webp', 'P20');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I59', 'Khung ảnh gỗ 3 in 1', 'images/products/p20_2.webp', 'P20');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I60', 'Khung ảnh gỗ 3 in 1', 'images/products/p21.webp', 'P20');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I61', 'Khung ảnh, tủ móc khóa, móc tr', 'images/products/p21_1.webp', 'P21');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I62', 'Khung ảnh, tủ móc khóa, móc tr', 'images/products/p22.webp', 'P21');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I63', 'Khung hình vintage triple cỡ l', 'images/products/p23.webp', 'P22');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I64', 'Khung ảnh handmade - thiệp han', 'images/products/p24.webp', 'P23');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I65', 'Khung ảnh kiểu Địa Trung Hải', 'images/products/p25.webp', 'P24');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I66', 'Khung ảnh vintage kiểu US Army', 'images/products/p26.webp', 'P25');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I67', 'Khung ảnh vintage trắng ngà', 'images/products/p27.webp', 'P26');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I68', 'Khung ảnh - móc treo FISH HOOK', 'images/products/p28.webp', 'P27');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I69', 'Khung ảnh gỗ và thạch cao Ivor', 'images/products/p28_1.webp', 'P28');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I70', 'Khung ảnh gỗ và thạch cao Ivor', 'images/products/p28_2.webp', 'P28');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I71', 'Khung ảnh gỗ và thạch cao Ivor', 'images/products/p29.webp', 'P28');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I72', 'Khung ảnh Hải Âu Mediterranea', 'images/products/p30.webp', 'P29');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I73', 'Khung ảnh Địa Trung Hải Kayak', 'images/products/p31.webp', 'P30');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I74', 'Khung ảnh vintage hoa văn vuôn', 'images/products/p32.webp', 'P31');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I75', 'Khung ảnh mèo Totoro', 'images/products/p32_1.webp', 'P32');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I76', 'Khung ảnh mèo Totoro', 'images/products/p32_2.webp', 'P32');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I77', 'Khung ảnh mèo Totoro', 'images/products/p33.webp', 'P32');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I78', 'Khung ảnh Staring time (lớn)', 'images/products/p33_1.webp', 'P33');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I79', 'Khung ảnh Staring time (lớn)', 'images/products/p33_2.webp', 'P33');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I80', 'Khung ảnh Staring time (lớn)', 'images/products/p34.webp', 'P33');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I81', 'Khung ảnh gỗ thông Rustic', 'images/products/p34_1.webp', 'P34');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I82', 'Khung ảnh gỗ thông Rustic', 'images/products/p34_2.webp', 'P34');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I83', 'Khung ảnh gỗ thông Rustic', 'images/products/p35.webp', 'P34');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I84', 'Khung ảnh Hải Âu Mediterranea', 'images/products/p36.webp', 'P35');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I85', 'Khung trang trí bàn hoa hồng s', 'images/products/p37.webp', 'P36');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I86', 'KHUNG ẢNH NGÔI NHÀ CỬA SỔ NÂU ', 'images/products/p37_1.webp', 'P37');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I87', 'KHUNG ẢNH NGÔI NHÀ CỬA SỔ NÂU ', 'images/products/p38.webp', 'P37');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I88', 'KHUNG ẢNH NGÔI NHÀ XE ĐẠP', 'images/products/p38_1.webp', 'P38');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I89', 'KHUNG ẢNH NGÔI NHÀ XE ĐẠP', 'images/products/p39.webp', 'P38');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I90', 'KHUNG ẢNH VÒNG ĐU QUAY VINTAGE', 'images/products/p40.webp', 'P39');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I91', 'Bì thư vintage Tem Việt', 'images/products/p40_1.webp', 'P40');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I92', 'Bì thư vintage Tem Việt', 'images/products/p40_2.webp', 'P40');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I93', 'Bì thư vintage Tem Việt', 'images/products/p41.webp', 'P40');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I94', 'Scrapbook That Time', 'images/products/p41_1.webp', 'P41');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I95', 'Scrapbook That Time', 'images/products/p41_2.webp', 'P41');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I96', 'Scrapbook That Time', 'images/products/p42.webp', 'P41');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I97', 'Scrapbook Sweet Mint', 'images/products/p42_1.webp', 'P42');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I98', 'Scrapbook Sweet Mint', 'images/products/p43.webp', 'P42');
INSERT INTO `image` (`id`, `name`, `path`, `productId`) VALUES ('I99', 'Scrapbook Fly That Time', 'images/products/p43_1.webp', 'P43');
